### PR TITLE
Fix unrendered "example" section

### PR DESCRIPTION
**Pull request by Rindrics**
#### Chores

- execute `tfplugindocs migrate` to let preexistent "Example Usage" section being recognized by registry website

#### Before

"Example Usage" section is not shown on site although [it exists in the code](https://github.com/SigNoz/terraform-provider-signoz/blob/9d19f500daba1061f03b77019893e634cc506530/docs/resources/alert.md?plain=1#L13):
https://registry.terraform.io/providers/SigNoz/signoz/0.0.4/docs/resources/alert

#### After

"Example Usage" section is recognized and shown on site:
https://registry.terraform.io/providers/Rindrics/signoz/0.0.1/docs/resources/alert

### Note

- I wanted to delete & ignore `docs/*`, but left it as it is because we cannot dynamically include them to the releases
  - because [`.Name` and `.Path` template variable](https://arc.net/l/quote/ybivztyu) is paid-feature of goreleaser

### CODE REVIEW

**Comment by grandwizard28** [comment]
Thank you for your contribution @Rindrics

**Comment by Rindrics** [comment]
thanks, I converted this PR to draft because I found something to check.

**Comment by Rindrics** [comment]
I surveyed whether we can remove & ignore `docs/` but finally found we cannot.
- I wrote I found to the description: https://github.com/SigNoz/terraform-provider-signoz/pull/23#issue-2609389822

**Comment by Rindrics** [comment]
would you take a look at this PR? @grandwizard28

**Review by grandwizard28 — APPROVED** [review]

**Pull request merged**
